const list =[
    {
        
        name:"电脑",
        type:[
            {name:"笔记本"},
            {name:"台式机"}
        ]
    },
    {
        name:"冰箱/冷柜",
        type:[
            {name:'晶弘',value:''},
            {name:'美的',value:''},
            {name:'海尔',value:''},
            {name:'容声',value:''},
            {name:'新飞',value:''},
            {name:'海信',value:''},
            {name:'TCL',value:''},
            {name:'卡萨帝',value:''},
            {name:'格兰仕',value:''},
            {name:'美菱',value:''},
            {name:'西门子',value:''},
            {name:'其他品牌',value:''},
        ]
    },
    {
        name:"热水器",
        type:[
            {name:"华帝",value:""},
            {name:"樱花",value:""},
            {name:"帅康",value:""},
            {name:"奥特朗",value:""},
            {name:"美的",value:""},
            {name:"海尔",value:""},
            {name:"卡萨帝",value:""},
            {name:"统帅",value:""},
            {name:"万和",value:""},
            {name:"AO史密斯",value:""},
            {name:"万家乐",value:""},
            {name:"阿里斯顿",value:""},
            {name:"西门子",value:""},
            {name:"其他品牌",value:""}
        ]
    },
    {
        name:"洗衣机",
        type:[
           {name:"美的",value:''},
           {name:"海尔",value:''},
           {name:"海信",value:''},
           {name:"TCL",value:''},
           {name:"卡萨帝",value:''},
           {name:"统帅",value:''},
           {name:"小天鹅",value:''},
           {name:"三洋",value:''},
           {name:"荣事达",value:''},
           {name:"小鸭",value:''},
           {name:"美菱",value:''},
           {name:"西门子",value:''},
           {name:"LG",value:''},
           {name:"其他品牌",value:''}
        ]
    },
    {
        name:"电视机",
        type:[
         {name:'三星',value:''},
         {name:'夏普',value:''},
         {name:'海尔',value:''},
         {name:'海信',value:''},
         {name:'TCL',value:''},
         {name:'统帅',value:''},
         {name:'长虹',value:''},
         {name:'创维',value:''},
         {name:'康佳',value:''},
         {name:'索尼',value:''},
         {name:'其他品牌',value:''}
        ]
    },
    {
        name:"空调",
        type:[
           {name:'美的',value:''},
           {name:'海尔',value:''},
           {name:'海信',value:''},
           {name:'卡萨帝',value:''},
           {name:'统帅',value:''},
           {name:'格力',value:''},
           {name:'科龙',value:''},
           {name:'志高',value:''},
           {name:'格兰仕',value:''},
           {name:'奥克斯',value:''},
           {name:'长虹',value:''}
        ]
    },
    {
        name:"中央空调",
        type:[
           {name:'春兰',value:''},
           {name:'日立',value:''},
           {name:'远大',value:''},
           {name:'美的',value:''},
           {name:'海尔',value:''},
           {name:'海信',value:''},
           {name:'格力',value:''},
           {name:'志高',value:''},
           {name:'奥克斯',value:''},
           {name:'长虹',value:''},
           {name:'西门子',value:''},
           {name:'其他品牌',value:''}
        ]
    },
    {
        name:"净水器",
        type:[
            {name:'立升',value:''},
            {name:'华尔康',value:''},
            {name:'美的',value:''},
            {name:'海尔',value:''},
            {name:'碧水源',value:''},
            {name:'TOSOT大松',value:''},
            {name:'安吉尔',value:''},
            {name:'沁园',value:''},
            {name:'道尔顿',value:''},
            {name:'格力',value:''},
            {name:'AO史密斯',value:''},
            {name:'爱惠浦',value:''},
            {name:'其他品牌',value:''}

        ]
    },
    {
        name:"厨房电器",
        type:[
            {name:'老板',value:''},
            {name:'方太',value:''},
            {name:'华帝',value:''},
            {name:'四季沐歌',value:''},
            {name:'鸿雁',value:''},
            {name:'金羚',value:''},
            {name:'欧普照明',value:''},
            {name:'桑普',value:''},
            {name:'美的',value:''},
            {name:'海尔',value:''},
            {name:'统帅',value:''},
            {name:'苏泊尔',value:''},
            {name:'其他品牌',value:''}
        ]
    },
    {
        name:"生活家电",
        type:[
           {name:'九阳',value:''},
           {name:'飞利浦',value:''},
           {name:'万宝',value:''},
           {name:'松下',value:''},
           {name:'奔腾',value:''},
           {name:'艾美特',value:''},
           {name:'美的',value:''},
           {name:'海尔',value:''},
           {name:'TOSOT大松',value:''},
           {name:'安吉尔',value:''},
           {name:'沁园',value:''},
           {name:'荣事达',value:''},
           {name:'亚都',value:''},
           {name:'其他品牌',value:''}
        ]
    },
    {
      name:"家居维修",
      type:[
        {name:'厨卫零修',value:''},
        {name:'水暖维修',value:''},
        {name:'门窗维修',value:''},
        {name:'地面维修',value:''},
        {name:'防水维修',value:''},
        {name:'墙面维修',value:''},
        {name:'吊顶隔墙',value:''},
        {name:'电路灯具',value:''}
      ]
    } 
]

module.exports =list;